; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s -passes=load-store-vectorizer -load-store-vectorizer-normalize-types | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Test basic case: vectorize i32 and <2 x i16> loads
define void @test_i32_and_v2i16_loads(ptr %p) {
; CHECK-LABEL: @test_i32_and_v2i16_loads(
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[L0_CAST:%.*]] = bitcast <4 x i16> [[TMP1]] to <2 x i32>
; CHECK-NEXT:    [[L0:%.*]] = extractelement <2 x i32> [[L0_CAST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    ret void
;
  %p1 = getelementptr i32, ptr %p, i64 1
  %l0 = load i32, ptr %p, align 4
  %l1 = load <2 x i16>, ptr %p1, align 4
  ret void
}

; Test basic case: vectorize i32 and <2 x i16> stores
define void @test_i32_and_v2i16_stores(ptr %p, i32 %v0, <2 x i16> %v1) {
; CHECK-LABEL: @test_i32_and_v2i16_stores(
; CHECK-NEXT:    [[V0_CAST:%.*]] = bitcast i32 [[V0:%.*]] to <2 x i16>
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i16> [[V0_CAST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <4 x i16> poison, i16 [[TMP1]], i32 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i16> [[V0_CAST]], i32 1
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x i16> [[TMP2]], i16 [[TMP3]], i32 1
; CHECK-NEXT:    [[V1_CAST:%.*]] = bitcast <2 x i16> [[V1:%.*]] to <2 x i16>
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x i16> [[V1_CAST]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i16> [[TMP4]], i16 [[TMP5]], i32 2
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <2 x i16> [[V1_CAST]], i32 1
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i16> [[TMP6]], i16 [[TMP7]], i32 3
; CHECK-NEXT:    store <4 x i16> [[TMP8]], ptr [[P:%.*]], align 4
; CHECK-NEXT:    ret void
;
  %p1 = getelementptr i32, ptr %p, i64 1
  store i32 %v0, ptr %p, align 4
  store <2 x i16> %v1, ptr %p1, align 4
  ret void
}

; Test with <4 x i8> and i32: should normalize to i8
define void @test_v4i8_and_i32_loads(ptr %p) {
; CHECK-LABEL: @test_v4i8_and_i32_loads(
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i8>, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[L1_CAST:%.*]] = bitcast <4 x i8> [[TMP3]] to i32
; CHECK-NEXT:    ret void
;
  %p1 = getelementptr <4 x i8>, ptr %p, i64 1
  %l0 = load <4 x i8>, ptr %p, align 4
  %l1 = load i32, ptr %p1, align 4
  ret void
}

; Test with float and i32: should normalize to i32
define void @test_float_and_i32_loads(ptr %p) {
; CHECK-LABEL: @test_float_and_i32_loads(
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i32>, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[L0_CAST:%.*]] = extractelement <2 x i32> [[TMP1]], i32 0
; CHECK-NEXT:    [[L0:%.*]] = bitcast i32 [[L0_CAST]] to float
; CHECK-NEXT:    [[L1:%.*]] = extractelement <2 x i32> [[TMP1]], i32 1
; CHECK-NEXT:    ret void
;
  %p1 = getelementptr float, ptr %p, i64 1
  %l0 = load float, ptr %p, align 4
  %l1 = load i32, ptr %p1, align 4
  ret void
}

; Test that chains split by aliasing are still handled correctly
define void @test_i32_and_v2i16_with_aliasing(ptr %p, ptr %q) {
; CHECK-LABEL: @test_i32_and_v2i16_with_aliasing(
; CHECK-NEXT:    [[L0:%.*]] = load i32, ptr [[P:%.*]], align 4
; CHECK-NEXT:    store i32 0, ptr [[Q:%.*]], align 4
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i32, ptr [[P]], i64 1
; CHECK-NEXT:    [[L1:%.*]] = load <2 x i16>, ptr [[P1]], align 4
; CHECK-NEXT:    ret void
;
  %l0 = load i32, ptr %p, align 4
  store i32 0, ptr %q, align 4
  %p1 = getelementptr i32, ptr %p, i64 1
  %l1 = load <2 x i16>, ptr %p1, align 4
  ret void
}

; Test non-contiguous accesses (should not vectorize)
define void @test_non_contiguous_i32_v2i16(ptr %p) {
; CHECK-LABEL: @test_non_contiguous_i32_v2i16(
; CHECK-NEXT:    [[L0:%.*]] = load i32, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[P2:%.*]] = getelementptr i32, ptr [[P]], i64 2
; CHECK-NEXT:    [[L1:%.*]] = load <2 x i16>, ptr [[P2]], align 4
; CHECK-NEXT:    ret void
;
  %l0 = load i32, ptr %p, align 4
  %p2 = getelementptr i32, ptr %p, i64 2
  %l1 = load <2 x i16>, ptr %p2, align 4
  ret void
}

; Test with three different types: i32, <2 x i16>, i16 (normalize to i16)
define void @test_three_types_i32_v2i16_i16(ptr %p) {
; CHECK-LABEL: @test_three_types_i32_v2i16_i16(
; CHECK-NEXT:    [[TMP1:%.*]] = load <5 x i16>, ptr [[P:%.*]], align 4
; CHECK-NEXT:    [[L0_CAST:%.*]] = bitcast <5 x i16> [[TMP1]] to <2 x i32>
; CHECK-NEXT:    [[L0:%.*]] = extractelement <2 x i32> [[L0_CAST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <5 x i16> [[TMP1]], <5 x i16> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[L2:%.*]] = extractelement <5 x i16> [[TMP1]], i32 4
; CHECK-NEXT:    ret void
;
  %p1 = getelementptr i32, ptr %p, i64 1
  %p2 = getelementptr i32, ptr %p, i64 2
  %l0 = load i32, ptr %p, align 4
  %l1 = load <2 x i16>, ptr %p1, align 4
  %l2 = load i16, ptr %p2, align 2
  ret void
}

; Test misaligned access with mixed types
define void @test_misaligned_i32_v2i16(ptr %p) {
; CHECK-LABEL: @test_misaligned_i32_v2i16(
; CHECK-NEXT:    [[L0:%.*]] = load i32, ptr [[P:%.*]], align 1
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i32, ptr [[P]], i64 1
; CHECK-NEXT:    [[L1:%.*]] = load <2 x i16>, ptr [[P1]], align 1
; CHECK-NEXT:    ret void
;
  %l0 = load i32, ptr %p, align 1
  %p1 = getelementptr i32, ptr %p, i64 1
  %l1 = load <2 x i16>, ptr %p1, align 1
  ret void
}

; Test without the flag enabled (should not vectorize mixed types)
; RUN: opt -S < %s -passes=load-store-vectorizer | FileCheck %s --check-prefix=NO-NORM

define void @test_without_normalization(ptr %p) {
; NO-NORM-LABEL: @test_without_normalization(
; NO-NORM-NEXT:    [[L0:%.*]] = load i32, ptr [[P:%.*]], align 4
; NO-NORM-NEXT:    [[P1:%.*]] = getelementptr i32, ptr [[P]], i64 1
; NO-NORM-NEXT:    [[L1:%.*]] = load <2 x i16>, ptr [[P1]], align 4
; NO-NORM-NEXT:    ret void
;
  %l0 = load i32, ptr %p, align 4
  %p1 = getelementptr i32, ptr %p, i64 1
  %l1 = load <2 x i16>, ptr %p1, align 4
  ret void
}

