; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=nvptx64-nvidia-cuda -S < %s -passes=load-store-vectorizer -load-store-vectorizer-normalize-types | FileCheck %s

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v32:32:32-v64:64:64-v128:128:128-n16:32:64"

; Test vectorization of mixed i32 and <2 x i16> loads in CUDA kernel
define void @cuda_mixed_type_loads(ptr addrspace(1) %base, ptr addrspace(1) %out) {
; CHECK-LABEL: @cuda_mixed_type_loads(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr addrspace(1) [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load <2 x i16>, ptr addrspace(1) [[PTR1]], align 4
; CHECK-NEXT:    [[OUT1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT:%.*]], i64 1
; CHECK-NEXT:    store i32 [[V0]], ptr addrspace(1) [[OUT]], align 4
; CHECK-NEXT:    store <2 x i16> [[V1]], ptr addrspace(1) [[OUT1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr addrspace(1) %base, i64 1
  %v0 = load i32, ptr addrspace(1) %base, align 4
  %v1 = load <2 x i16>, ptr addrspace(1) %ptr1, align 4
  %out1 = getelementptr i32, ptr addrspace(1) %out, i64 1
  store i32 %v0, ptr addrspace(1) %out, align 4
  store <2 x i16> %v1, ptr addrspace(1) %out1, align 4
  ret void
}

; Test vectorization of mixed type stores
define void @cuda_mixed_type_stores(ptr addrspace(1) %base, i32 %val0, <2 x i16> %val1) {
; CHECK-LABEL: @cuda_mixed_type_stores(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(1) [[BASE:%.*]], i64 1
; CHECK-NEXT:    store i32 [[VAL0:%.*]], ptr addrspace(1) [[BASE]], align 4
; CHECK-NEXT:    store <2 x i16> [[VAL1:%.*]], ptr addrspace(1) [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr addrspace(1) %base, i64 1
  store i32 %val0, ptr addrspace(1) %base, align 4
  store <2 x i16> %val1, ptr addrspace(1) %ptr1, align 4
  ret void
}

; Test with shared memory (address space 3)
define void @cuda_shared_mem_mixed_types(ptr addrspace(3) %base) {
; CHECK-LABEL: @cuda_shared_mem_mixed_types(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(3) [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr addrspace(3) [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load <2 x i16>, ptr addrspace(3) [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr addrspace(3) %base, i64 1
  %v0 = load i32, ptr addrspace(3) %base, align 4
  %v1 = load <2 x i16>, ptr addrspace(3) %ptr1, align 4
  ret void
}

; Test with float and i32 (same size, different types)
define void @cuda_float_i32_mixed(ptr addrspace(1) %base) {
; CHECK-LABEL: @cuda_float_i32_mixed(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr float, ptr addrspace(1) [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load float, ptr addrspace(1) [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr addrspace(1) [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr float, ptr addrspace(1) %base, i64 1
  %v0 = load float, ptr addrspace(1) %base, align 4
  %v1 = load i32, ptr addrspace(1) %ptr1, align 4
  ret void
}

