; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer -load-store-vectorizer-normalize-types -debug-only=load-store-vectorizer 2>&1 | FileCheck %s
; REQUIRES: asserts

; This test verifies that all split functions (splitChainByContiguity, 
; splitChainByAlignment, and vectorizeChain) consistently use the normalized
; type when type normalization is enabled. Without the fix, they would use
; different types, leading to suboptimal splitting decisions.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"

; Test that all split stages use i16 as the normalized type for {i32, <2 x i16>}
; The original heuristic would pick i32, but normalization should use i16 (GCD)
define void @test_consistent_i16_normalization(ptr %base) {
; CHECK-LABEL: @test_consistent_i16_normalization(
; CHECK: LSV: splitChainByContiguity
; CHECK: Using normalized type: i16
; CHECK: LSV: splitChainByAlignment
; CHECK: Using normalized type: i16
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load <2 x i16>, ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  %v0 = load i32, ptr %base, align 4
  %v1 = load <2 x i16>, ptr %ptr1, align 4
  ret void
}

; Test with three types: i32, <2 x i16>, i16 - normalized type should be i16
define void @test_consistent_three_types(ptr %base) {
; CHECK-LABEL: @test_consistent_three_types(
; CHECK: LSV: splitChainByContiguity
; CHECK: Using normalized type: i16
; CHECK: LSV: splitChainByAlignment
; CHECK: Using normalized type: i16
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[PTR2:%.*]] = getelementptr i32, ptr [[BASE]], i64 2
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load <2 x i16>, ptr [[PTR1]], align 4
; CHECK-NEXT:    [[V2:%.*]] = load i16, ptr [[PTR2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  %ptr2 = getelementptr i32, ptr %base, i64 2
  %v0 = load i32, ptr %base, align 4
  %v1 = load <2 x i16>, ptr %ptr1, align 4
  %v2 = load i16, ptr %ptr2, align 2
  ret void
}

; Test with <4 x i8> and i32 - normalized type should be i8
define void @test_consistent_i8_normalization(ptr %base) {
; CHECK-LABEL: @test_consistent_i8_normalization(
; CHECK: LSV: splitChainByContiguity
; CHECK: Using normalized type: i8
; CHECK: LSV: splitChainByAlignment
; CHECK: Using normalized type: i8
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr <4 x i8>, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load <4 x i8>, ptr [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr <4 x i8>, ptr %base, i64 1
  %v0 = load <4 x i8>, ptr %base, align 4
  %v1 = load i32, ptr %ptr1, align 4
  ret void
}

; Test stores with consistent normalization
define void @test_consistent_stores(ptr %base, i32 %val0, <2 x i16> %val1) {
; CHECK-LABEL: @test_consistent_stores(
; CHECK: LSV: splitChainByContiguity
; CHECK: Using normalized type: i16
; CHECK: LSV: splitChainByAlignment
; CHECK: Using normalized type: i16
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    store i32 [[VAL0:%.*]], ptr [[BASE]], align 4
; CHECK-NEXT:    store <2 x i16> [[VAL1:%.*]], ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  store i32 %val0, ptr %base, align 4
  store <2 x i16> %val1, ptr %ptr1, align 4
  ret void
}

; Test that uniform types don't trigger normalization
define void @test_no_normalization_uniform(ptr %base) {
; CHECK-LABEL: @test_no_normalization_uniform(
; CHECK-NOT: Using normalized type
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  %v0 = load i32, ptr %base, align 4
  %v1 = load i32, ptr %ptr1, align 4
  ret void
}

