; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer -load-store-vectorizer-normalize-types | FileCheck %s

; Test basic vectorization of i32 and <2 x i16> loads on X86
define void @simple_i32_v2i16_loads(ptr %base) {
; CHECK-LABEL: @simple_i32_v2i16_loads(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load <2 x i16>, ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  %v0 = load i32, ptr %base, align 4
  %v1 = load <2 x i16>, ptr %ptr1, align 4
  ret void
}

; Test basic vectorization of i32 and <2 x i16> stores on X86
define void @simple_i32_v2i16_stores(ptr %base, i32 %val0, <2 x i16> %val1) {
; CHECK-LABEL: @simple_i32_v2i16_stores(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    store i32 [[VAL0:%.*]], ptr [[BASE]], align 4
; CHECK-NEXT:    store <2 x i16> [[VAL1:%.*]], ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  store i32 %val0, ptr %base, align 4
  store <2 x i16> %val1, ptr %ptr1, align 4
  ret void
}

; Test vectorization with <4 x i8> and i32
define void @v4i8_i32_loads(ptr %base) {
; CHECK-LABEL: @v4i8_i32_loads(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr <4 x i8>, ptr [[BASE:%.*]], i64 1
; CHECK-NEXT:    [[V0:%.*]] = load <4 x i8>, ptr [[BASE]], align 4
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[PTR1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr <4 x i8>, ptr %base, i64 1
  %v0 = load <4 x i8>, ptr %base, align 4
  %v1 = load i32, ptr %ptr1, align 4
  ret void
}

; Verify that without the flag, mixed types are NOT vectorized
; RUN: opt -S < %s -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer | FileCheck %s --check-prefix=NO-FLAG

define void @without_flag_i32_v2i16(ptr %base) {
; NO-FLAG-LABEL: @without_flag_i32_v2i16(
; NO-FLAG-NEXT:  entry:
; NO-FLAG-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr [[BASE:%.*]], i64 1
; NO-FLAG-NEXT:    [[V0:%.*]] = load i32, ptr [[BASE]], align 4
; NO-FLAG-NEXT:    [[V1:%.*]] = load <2 x i16>, ptr [[PTR1]], align 4
; NO-FLAG-NEXT:    ret void
;
entry:
  %ptr1 = getelementptr i32, ptr %base, i64 1
  %v0 = load i32, ptr %base, align 4
  %v1 = load <2 x i16>, ptr %ptr1, align 4
  ret void
}

